apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: uda-cap-deployment
spec:
  selector:
    matchLabels:
      app: capstone
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
      - name: udacity-capstone
        image: harshitha95/capstone:v1
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: uda-cap-deployment
  labels:
    app: uda-cap-deployment
spec:
  type: LoadBalancer
  selector:
    app: uda-cap-deployment
  ports:
    - port: 8000
      targetPort: 80
      protocol: TCP