apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-rolling-update
  labels: 
    app: capstone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstone
  template:
    metadata:
      labels:
        app: capstone
        role: rolling-update
    spec:
      containers:
      - name: capstone-html-container
        image: harshitha95/capstone:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

